[package]
name = "difference_engine"
version = "0.1.0"
authors = ["Alexander Ronald Altman <alexanderaltman@me.com>"]

[dependencies]

[lib]
name = "difference_engine"
path = "src/lib.rs"

[[bin]]
name = "deng"
path = "src/main.rs"
